version: "3"
services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - ratelimit-network

  ratelimit:
    image: envoyproxy/ratelimit:master
    command: /bin/ratelimit
    ports:
      - 8080:8080
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
    networks:
      - ratelimit-network
    volumes:
      - ./examples/ratelimit/conf:/data/ratelimit/config
    environment:
      - USE_STATSD=false
      - STATSD_PORT=9125
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit
      - RUNTIME_WATCH_ROOT=false

  envoy-proxy:
    image: envoyproxy/envoy-dev:latest
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--service-node proxy"
      - "--service-cluster proxy"
      - "--config-path /etc/envoy/envoy.yaml"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level debug"
    volumes:
      - ./examples/envoy/proxy-with-use_remote_address.yaml:/etc/envoy/envoy.yaml
    networks:
      - ratelimit-network
    expose:
       - "8888"
       - "8001"
    depends_on:
      - ratelimit
    ports:
       - "8888:8888"
       - "8001:8001"

  envoy-mock:
    image: envoyproxy/envoy-dev:latest
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--service-node mock"
      - "--service-cluster mock"
      - "--config-path /etc/envoy/envoy.yaml"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level info"
    volumes:
      - ./examples/envoy/mock.yaml:/etc/envoy/envoy.yaml
    networks:
      - ratelimit-network
    expose:
       - "9999"
    ports:
       - "9999:9999"

networks:
  ratelimit-network:
